### ISSUE TITLE
Camera to world error

### ISSUE THREAD

**Issue by colek42** [smidm/camera.py#1]
Fort camera to world I think the calulation should be:

P = K[R^t | -R^t*T]

newP = P[cols 1-2] | (P[col3] \* z + P[col4])

newP^-1 x  [u, v, 1]^t = [a, b, c]

Xworld = a/c
Yworld = b/c
Zworld = z

where 
z = world altitude
K = Camera Transform
R^t, transpose of R
T = Xw  (Camera world coords)

Your code helped me a ton with my problem, thanks for posting.

**Comment by smidm** [comment]
Hi! You are talking about image_to_world(self, image_px, z) function, aren't you?

I would say that the function is exactly doing the steps you've described:

```
    def image_to_world(self, image_px, z):
        """
        Project image points with defined world z to world coordinates.
        :param image_px: image points
        :type image_px: numpy.ndarray, shape=(2 or 3, n)
        :param z: world z coordinate of the projected image points
        :type z: float
        :return: n projective world coordinates
        :rtype: numpy.ndarray, shape=(4, n)
        """
        if image_px.shape[0] == 2:
            image_px = e2p(image_px)
        image_undistorted = self._undistort(image_px)
        tmpP = np.hstack((self.P[:, [0, 1]], self.P[:, 2, np.newaxis] * z + self.P[:, 3, np.newaxis]))  # newP = P[cols 1-2] | (P[col3] * z + P[col4])
        return np.linalg.inv(tmpP).dot(image_undistorted)  # newP^-1 x [u, v, 1]^t = [a, b, c]
```

Concerning this camera matrix decomposition: `P = K[R^t | -R^t*T]`. You understand R differently than the R in the code. The Camera.R is the _world orientation in the camera coordinate frame_, but your R is the Camera.R inverted (or transposed) - the _camera orientation in the world coordinate frame_. See http://cmp.felk.cvut.cz/cmp/courses/TDV/2013W/lectures/tdv-2013-all.pdf page 21, "Changing The Outer (World) Reference Frame". I should document this.

Or is the error somewhere else? Did I miss something?

**Comment by colek42** [comment]
I couldn't tell you for sure.  I needed to get world locations (UTM coordinates) from a UAV camera.  I was verifying visually with a map library, and everything looked good.  My code is in Java, when I get a chance I will grab the bits out that have to do with this and share them with you.

**Comment by smidm** [comment]
You can try to use the camera.py with your R transposed and maybe also 
T multiplied by -1. This should convert your R, T to camera.py R,t.

colek42 notifications@github.com napsal Pá, dub 17, 2015 v 5∶29 :
